---
title: "Check sources"
format: html
editor: source
---

```{r}
library(dplyr)
library(readr)
library(tinyplot)
options(scipen = 99)
```

```{r}
szu <- read_rds("data-interim/szu-uo-all-do2023.rds")
sp <- read_rds("data-interim/sp_platy_uo.rds")
```

```{r}
szu_s <- szu |> 
  filter(rok == 2022, faze_rozpoctu == "SKUT") |> 
  select(kap_zkr, kap_kod, platy_szu = platy, pocet_zamestnancu, rok)
```

```{r}
sp_s <- sp |> 
  filter(rok == 2022, promenna %in% c("platy")) |> 
  select(kap_kod, platy_sp = skut, rok)
  
```

```{r}
both <- left_join(szu_s, sp_s, by = join_by(kap_kod, rok)) |> 
  mutate(rozdil = round(platy_szu - platy_sp),
         across(starts_with("platy"), \(x) x/1e6))
both
```

```{r}
tinyplot(platy_szu ~ platy_sp | kap_zkr, data = both,
         palette = "dark", pch  = 16,
         grid = TRUE, frame = FALSE)
```

```{r}
plt(
  Sepal.Length ~ Petal.Length | Species, 
  data = iris,
  palette = "dark", pch  = 16,
  grid = TRUE, frame = FALSE
)
```

```{r}
op = tpar(
  bty    = "n",           # No box (frame) around the plot 
  family = "IBM Plex Sans", # Use R's Hershey font instead of Arial default
  grid   = TRUE,          # Add a background grid
  las    = 1,             # Horizontal axis tick labels
  pch    = 16             # Filled points as default
)

aq = airquality
aq$Month = factor(month.abb[aq$Month], levels = month.abb[5:9])

plt(
  Temp ~ Day | Month, data = aq,
  type = "b",
  palette = palette.colors(palette = "tableau", alpha = 0.5),
  main = "Daily temperatures by month"
)
```
